export interface SelectedMovieData {
  backdrop_path?: string,
  budget?: number,
  genres?: [],
  homepage?: string,
  overview: string,
  popularity?: number,
  poster_path?: string,
  production_companies?: [],
  release_date?: string,
  revenue?: number,
  runtime: number,
  spoken_languages?: [],
  status?: string,
  tagline?: string,
  title: string,
  video?: boolean,
  vote_average: number,
  vote_count?: number
}